version: "3.8"


services:
    db:
      container_name: blog_db
      image: mariadb:10.5.9
      env_file: 
        - db.env
      volumes:
        - db_volume:/var/lib/mysql
      ports:
        - 3307:3306
    
volumes: 
    db_volume:
